version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: usermanagement
      MYSQL_ROOT_PASSWORD: Priyam00
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: user-management-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: always

volumes:
  mysql_data:
