version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: usermanagement
      MYSQL_ROOT_PASSWORD: Priyam00
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: user-management-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: UserManagement
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/usermanagement?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Priyam00
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      JWT_SECRET: MySuperSecretKeyForJWTTokenShouldBeLongEnough
      JWT_EXPIRATION: 86400000
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,metrics,info
      MANAGEMENT_ENDPOINTS_HEALTH_SHOW_DETAILS: always
      MANAGEMENT_INFO_ENV_ENABLED: "true"
      MANAGEMENT_ENDPOINT_METRICS_ENABLED: "true"
      MANAGEMENT_HEALTH_DB_ENABLED: "true"
      SPRINGDOC_API_DOCS_ENABLED: "true"
      SPRINGDOC_SWAGGER_UI_ENABLED: "true"
    restart: always

volumes:
  mysql_data:
