name: Deploy to GCE using Docker (Self-hosted Runner)

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_IMAGE }} .

      - name: Stop and Remove Existing Container (if any)
        run: |
          docker stop user-management-container || echo "No running container to stop"
          docker rm user-management-container || echo "No existing container to remove"

      - name: Run Docker Container with Secrets
        run: |
          docker run -d \
            --name user-management-container \
            -e SPRING_PROFILES_ACTIVE=prod \
            -e DB_URL="${{ secrets.DB_URL }}" \
            -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
            -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            -e JWT_EXPIRATION="${{ secrets.JWT_EXPIRATION }}" \
            -e SPRINGDOC_API_DOCS_ENABLED=true \
            -e SPRINGDOC_SWAGGER_UI_ENABLED=true \
            -p 8080:8080 \
            ${{ secrets.DOCKER_IMAGE }}
